name: Build docker image

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/shitcloud/todo:${{ github.sha }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/shitcloud/todo:latest
